# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          - name: Sql-Lint
  # You may pin to the exact commit or the version.
  # uses: Bidaya0/sql-lint-in-action@89adf42e9a8e8b4016225560c89e318a3b39e1cf
  uses: Bidaya0/sql-lint-in-action@v0.0.2
  with:
    # The path of sql file located
    path: # default is .
    # The host of sql host
    host: # optional, default is 
    # The user of sql database
    user: # optional, default is root
    # The password of sql database
    password: # optional, default is 
    # The driver of sql database
    driver: # optional, default is mysql
    # The port of sql database
    port: # optional, default is 3306
    # The errors will be ignore
    ignore_errors: # optional, default is 
